version: '3.6'

services:
  eureka-service:
    image: andrey2702/eureka-service:prod
    restart: always

# postgres - создать базы данных, подключится к ним
# redis, подключится
# keycloak, создать все рилмы, пользователей, мапперы
# minio, подключится, создать топик
# kafka, подключится, создать топик
# мониторинг, логирование

# актуализировать все конфиги в конфиг сервисе, проверить локальный запуск
# вынести наиболее палевные конфиги в конфиг compose-stack
# поднять все сервисы, сделать простые операции

# написать тесты, залить

# вебинар по микросервисам

# курсач, презентация


