version: '3.6'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0-0
    container_name: keycloak
    command: start-dev --http-port=8081
    ports:
      - "8081:8081"
    environment:
      - "KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}"
      - "KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}"

  redis:
    image: redis:6.2.11
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"

  kafka:
    image: bitnami/kafka:3.0.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - "MINIO_ROOT_USER=${MINIO_USERNAME}"
      - "MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}"

  postgres:
    image: postgres:15-bullseye
    container_name: postgres
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "5432:5432"

  eureka-service:
    image: andrey2702/eureka-service:prod
    ports:
      - "8761:8761"
    restart: always

  gateway-service:
    image: andrey2702/gateway-service:prod
    restart: always

  config-service:
    image: andrey2702/config-service:prod
    restart: always
    environment:
      - "CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}"

  auth-service:
    image: andrey2702/auth-service:prod
    ports:
      - "9101:9101"
    restart: always


# postgres - создать базы данных, подключится к ним
# redis, подключится
# keycloak, создать все рилмы, пользователей, мапперы
# minio, подключится, создать топик
# kafka, подключится, создать топик
# мониторинг, логирование

# поднять все сервисы, сделать простые операции
# написать тесты, залить

# вебинар по микросервисам

# курсач, презентация