version: '3.6'

services:
  eureka-service:
    image: andrey2702/eureka-service:prod
    ports:
      - 8761:8761
    restart: always

  gateway-service:
    image: andrey2702/gateway-service:prod
    restart: always

  config-service:
    image: andrey2702/config-service:prod
    restart: always
    environment:
      - "CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}"

# postgres - создать базы данных, подключится к ним
# redis, подключится
# keycloak, создать все рилмы, пользователей, мапперы
# minio, подключится, создать топик
# kafka, подключится, создать топик
# мониторинг, логирование

# поднять все сервисы, сделать простые операции
# написать тесты, залить

# вебинар по микросервисам

# курсач, презентация


